methods/availableNumbers/getAvailableNumbersLocal.md
methods/availableNumbers/postAvailableNumbersLocal.md

This is designed to fix https://github.com/Bandwidth/ap-docs/issues/57

Make requirements more clear

---

apiCallbacks/sms.md

https://bandwidth.codefactori.com/browse/MV-65

add toll free error codes

---

SUMMARY.md
bxml/bxmlConcepts.md

The trello card has a list of items that need to be checked or changed. There are a few parts I added that I do not know if are necessary. We will definitely edit this but here is a great start.

First draft of BXMLConcepts

---

bxml/buildingBlocks/about.md
bxml/buildingBlocks/playAudio.md
bxml/buildingBlocks/record.md
bxml/buildingBlocks/speakSentence.html
bxml/buildingBlocks/speakSentence.md

Bxml steph

---

layouts/header.html

Removing dropdown

---

SUMMARY.md
layouts/header.html

Changed links to https

---

SUMMARY.md
apiCallbacks/incomingCall.md
bxml/callBacks/incomingCall.md

I'v been doing a lot more BXML tutorials and call flows and this came up a few times.  Must have missed this one as it's mostly ignored when using BXML, but still worth a call out.

add incoming call event to BXML callbacks

---

bxml/callBacks/answer.md

Adds the `tag` parameter for the `GET` answer event for BXML

add tag to answer event

---

methods/media/putMediaMediaName.md

Updated markdown from Nathan Miles

---

book.json

- [ x] I made sure that the site looks great and functions perfectly live
- [ x] I ran splell check
- [ x] I'm ready for these changes to be made live

Updated usabillaId in book.json

---

rateLimits/callRateLimits.md
rateLimits/messageRateLimits.md
rateLimits/resourceRateLimits.md

Initial stab at fleshing out examples for common retry methods

---

apiCallbacks/audio.md

- [*] I made sure that the site looks great and functions perfectly live
- [*] I'm ready for these changes to be made live

Fixed incorrect status value in example.

---

rateLimits/messageRateLimits.md

add more error docs for queue full (messaging)

---

methods/phoneNumbers/postPhoneNumbersNumberId.md

Added clearing of application by setting applicationId to "" in docs

---

methods/phoneNumbers/getPhoneNumbers.md

Add get phone numbers parameter example

---

methods/applications/postApplications.md

Change 'phone number' to 'phone numbers'

---

methods/transcriptions/transcriptions.md

Removed beta button

---

methods/applications/postApplications.md

Added comment regarding one of the callback urls must be set

---

rateLimits/messageRateLimits.md

Added note about SMS and MMS default rate limits being the same

---

bxml/verbs/gather.md

Fixed hellow typo

---

bxml/callBacks/answer.md
bxml/callBacks/incomingCall.md

Added BXML SIP Diversion header docs

---

methods/phoneNumbers/postImportPhoneNumber.md

Add ruby csharp code sample for import phone number

---

rateLimits/resourceRateLimits.md

Fixed dead links

---

book.json

Updated themes version to 1.9.11

---

methods/bridges/getBridges.md
methods/bridges/getBridgesBridgeId.md

- [ *] I made sure that the site looks great and functions perfectly live
- [ *] I ran splell check
- [ *] I'm ready for these changes to be made live

Changed word here to below indicating table below

---

README.md
bxml/bxml.md
methods/account/getAccountTransactions.md

Fix from date to date reversal

---

SUMMARY.md
styles/website.css

- [ *] I made sure that the site looks great and functions perfectly live
- [ *] I ran spell check
- [ *] I'm ready for these changes to be made live

Added headers to left nav

---

bxml/callBacks/recording.md

Removed unneeded state value and reorder docs to fit the code example

---

SUMMARY.md
bxml/bxmlCallbacks.md
bxml/callBacks/callTimeout.md

add GET request example for timeout

---

methods/availableNumbers/postAvailableNumbersLocal.md
methods/availableNumbers/postAvailableNumbersTollFree.md

Added note about post request params being url parameters

---

methods/account/getAccountTransactions.md
methods/availableNumbers/getAvailableNumbersLocal.md
methods/availableNumbers/getAvailableNumbersTollFree.md
methods/availableNumbers/postAvailableNumbersLocal.md

Fixed curl commands that had a trailing & to be copy-paste correct

---

methods/availableNumbers/postAvailableNumbersLocal.md

Maximum number order 10

---

methods/transcriptions/transcriptions.md

Clarified purpose of the transcription resource

---

bxml/bxmlOverview.md

Fixed sentence with the getting started setup guide link

---

methods/calls/calls.md
methods/messages/messages.md

Fixed recieve typos (except bxml/bxmlOverview.md. That's taken care of in another PR)

---

SUMMARY.md
sipDiversionHeader/sipDiversionHeader.md

Specified old sip diversion header information to be for inbound sip

---

methods/conferences/conferences.md
methods/conferences/postConferencesConferenceIdMembers.md

Specified 20 member limit for conferences

---

apiCallbacks/sms.md
methods/messages/getMessages.md
methods/messages/getMessagesMessageId.md

Fixed message not acknowledge typo

---

methods/restApi.md

Add sdk link

---

rateLimits/messageRateLimits.md

Mv 593 confusing error message rate limits update docs

---

rateLimits/messageRateLimits.md

Fixed bad request example

---

apiCallbacks/answer.md
apiCallbacks/confSpeak.md
apiCallbacks/gather.md
apiCallbacks/incomingCall.md
apiCallbacks/recording.md
apiCallbacks/sms.md
apiCallbacks/speak.md

DX-217 - Update User Agent

---

SUMMARY.md
rateLimits.md
rateLimits/futureChanges.md

DX-468 future rate limit changes (To be merged June 3rd at 2pm EST)

---

bxml/verbs/gather.md
bxml/verbs/playAudio.md

DX-461 - Update docs for new PlayAudio repeat feature

---

apiCallbacks/sms.md
methods/messages/getMessages.md
methods/messages/getMessagesMessageId.md

Adds previously forgotten 'bout error codes

update with error codes

---

methods/messages/getMessages.md
methods/messages/getMessagesMessageId.md
methods/messages/redactMessageText.md

update retention to 3 days
